app: 
  env: local
  port: 8888
  app_name: gin-app
  app_url: http://localhost

log:
  level: info
  root_dir: ./storage/logs
  filename: app.log
  format:
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true

database:
  driver: mysql
  host: 117.50.179.8
  port: 13306
  database: gin
  username: root
  password: root
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info
  enable_file_log_writer: true
  log_filename: sql.log

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:

jwt:
  secret: 3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800

storage:
  default: local # 默认驱动
  disks:
    local:
      root_dir: ./storage/app # 本地存储根目录
      app_url: http://localhost:8888/storage # 本地图片 url 前部
    ali_oss:
      access_key_id:
      access_key_secret:
      bucket:
      endpoint:
      is_ssl: true # 是否使用 https 协议
      is_private: false # 是否私有读
    qi_niu:
      access_key:
      bucket:
      domain:
      secret_key:
      is_ssl: true
      is_private: false

